config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :admin do
    resources :contests do
        collection do
          patch :approve
        end
    end
    root "contests#index"
  end

  resources :contests, only:[:index, :show] do
    collection do
      post :enroll
      get :dashboard
    end
  end
  root "contests#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/contest.rb
class Contest < ApplicationRecord
  mount_uploader :picture, FileUploader

  has_many :user_contests
  has_many :users, through: :user_contests
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  enum role: [:participant, :admin]
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      # user.name = auth.info.name   # assuming the user model has a name
      # user.avatar = auth.info.image # assuming the user model has an image
    end
  end
  
  has_many :user_contests
  has_many :contests, through: :user_contests

end

app/models/user_contest.rb
class UserContest < ApplicationRecord
  belongs_to :user
  belongs_to :contest
  
  enum status: [:pending, :approved]
end

app/controllers/admin/contests_controller.rb
class Admin::ContestsController < ApplicationController

  before_action :authenticate_user!
  before_action :check_admin

  def index
    @contests = Contest.all
    @pending_user_contests = UserContest.all.length > 0 ? UserContest.where(status: "pending") : []
  end

  def show
    @contest = Contest.find(params[:id])
    approved_user_ids = UserContest.where(status: "approved").select(:user_id)
    @users = @contest.users.where(id: approved_user_ids )
  end

  def new
    @contest = Contest.new
  end

  def create
    @contest = Contest.new(contest_params)
    if @contest.save
      redirect_to admin_root_path
    else
      render 'new'
    end
  end

  def edit
    @contest = Contest.find(params[:id])
  end

  def update
    @contest = Contest.find(params[:id])
    if @contest.update(contest_params)
      redirect_to admin_root_path
    else
      render 'edit'
    end
  end

  def destroy
    @contest = Contest.find(params[:id])
    @contest.destroy
    redirect_to admin_root_path
  end

  def approve
    UserContest.where(contest_id: params[:contest_id], user_id: params[:user_id]).first.update(
                      status: "approved")
  end

  private
  def check_admin
    flash[:notice_admin] = "Your account is not allowed to access the admin page."
    redirect_to root_path unless current_user.admin?
  end

  def contest_params
    params.require(:contest).permit(:name, :description, :picture, :start_date, :end_date)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :role, :total_friends])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :role, :total_friends])
  end
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController

  require 'fb_graph2'

  def index
    @enrolled_contests = current_user ? current_user.contests : []
    enrolled_contest_ids = @enrolled_contests.size > 0 ? @enrolled_contests.select(:id) : []
    @contests = Contest.where.not(id: enrolled_contest_ids)

  end

  def show
    @contest = Contest.find(params[:id])
  end

  def enroll
    @contest = Contest.find(params[:contest_id])

    current_user.contests << @contest unless current_user.contests.include?(@contest)
  end

  def dashboard
    enrolled_contest_ids = UserContest.where(user_id: current_user.id,
                                             status: "approved").select(:contest_id)
    @contests = Contest.where(id: enrolled_contest_ids )
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  require 'fb_graph2'

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    access_token = request.env["omniauth.auth"]["credentials"]["token"]
    # # Returns true if the record is persisted, 
    # i.e. it’s not a new record and it was not destroyed, otherwise returns false.
    if @user.persisted?
      user_uid = @user.uid
      user = FbGraph2::User.new(user_uid).authenticate(access_token).fetch
      friend_count = user.friends.summary["total_count"]
      avatar_url = user.picture.url
      @user.update(total_friends: friend_count, avatar: avatar_url)
      
      sign_in_and_redirect @user#, :event => :authentication #this will throw if @user is not activated
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to root_path
    end
  end

  def failure
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/contests/_form.html.erb
<%= form_for [:admin, @contest] do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :picture %>
    <%= f.file_field :picture, class: 'btn btn-default' %>
  </div>

  <!-- <img alt="preview" width="100" height="100" id="preview_image" /> -->
  <div class="gallery">
    
  </div>

  <br>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.cktext_area :description, class: 'form-control js-ckeditor' %>
  </div>
  <div class="row">
    <div class="form-group col-md-5" style="float: left;" >
      <%= f.label :start_date %>
      <%= f.date_select :start_date, value: Date.today, class: 'form-control'%>
    </div>
    <div class="form-group col-md-5" style="float: right;" >
      <%= f.label :end_date %>
      <%= f.date_select :end_date, value: Date.today, class: 'form-control'%>
    </div>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-primary pull-right' %>
  </div>
<% end %>

app/views/admin/contests/edit.html.erb
<div class="col-md-10 col-md-offset-1" style="box-shadow: 0px 3px 15px #888888; padding: 0; ">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4><b><%= @contest.name %></b></h4>
    </div>
    <div class="panel-body">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/admin/contests/index.html.erb
<div class="row" style="margin-bottom: 20px;">
  <div style="margin-right: 18px;">
    <%= link_to "New Contest", new_admin_contest_path, class: "btn btn-primary pull-right" %>
  </div>
</div>
<div class="row admin-page">
  <div class="col-sm-4">
    <div class="admin-sidebar">
      <table class="table">
        <thead>
          <tr>
            <th>Email</th>
            <th>Contest</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @pending_user_contests.each do |pending_user_contest| %>
            <tr id="admin_row_<%= pending_user_contest.contest_id %>">
              <td><%= pending_user_contest.user.email %></td>
              <td><%= pending_user_contest.contest.name %></td>
              <td><button class="btn btn-primary btn_approve" contest_id = <%= pending_user_contest.contest_id %> user_id = <%= pending_user_contest.user_id %> >Approve</button></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    
  </div>

  <div class="col-sm-8">
    <div class="admin-main">
      <table class="table">
        <thead>
          <tr>
            <th>Image</th>
            <th>Name</th>
            <th>Start_date</th>
            <th>End_date</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @contests.each do |contest| %>
            <tr>
              <td><%= image_tag contest.picture.small_thumb.url %></td>
              <td><%= link_to contest.name, admin_contest_path(contest.id) %></td>
              <td><%= contest.start_date.to_formatted_s(:short) %></td>
              <td><%= contest.end_date.to_formatted_s(:short) %></td>
              <td><%= link_to "Edit", edit_admin_contest_path(contest.id) %> -- <%= link_to "Delete", admin_contest_path(contest.id), method: :delete, data: {confirm: 'Are you sure?'} %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/contests/new.html.erb
<div class="col-md-10 col-md-offset-1" style="box-shadow: 0px 3px 15px #888888; padding: 0; ">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4><b>NEW CONTEST</b></h4>
    </div>
    <div class="panel-body">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/admin/contests/show.html.erb
<div>
  <% @users.each do |user| %>
    <div class="col-sm-3">
      <div class="card hovercard">
        <div class="card-background">
            <img class="card-bkimg" alt="" src="http://lorempixel.com/100/100/people/9/">
        </div>
        <div class="useravatar">
            <img alt="" src=<%= user.avatar %>>
        </div>
        <div class="card-info"> <span class="card-title"><%= user.email %></span>

        </div>
      </div>
      <div class="btn-pref btn-group btn-group-justified btn-group-lg" role="group" aria-label="...">
        <div class="btn-group" role="group">
            <button type="button" id="stars" class="btn btn-primary" href="#tab1" data-toggle="tab"><span class="glyphicon glyphicon-star" aria-hidden="true">Friends</span>
                <div class="hidden-xs"><%= user.total_friends %></div>
            </button>
        </div>
        <div class="btn-group" role="group">
            <button type="button" id="favorites" class="btn btn-default" href="#tab2" data-toggle="tab"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                <div class="hidden-xs">""</div>
            </button>
        </div>
        <div class="btn-group" role="group">
            <button type="button" id="following" class="btn btn-default" href="#tab3" data-toggle="tab"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                <div class="hidden-xs">""</div>
            </button>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/contests/dashboard.html.erb
<h4><b>ENROLL CONTEST(S)</b></h4>
<table class="table">
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Start_date</th>
      <th>End_date</th>
    </tr>
  </thead>
  <tbody>
    <% @contests.each do |contest| %>
      <tr>
        <td><%= image_tag contest.picture.small_thumb.url %></td>
        <td><%= contest.name %></td>
        <td><%= contest.start_date.to_formatted_s(:short) %></td>
        <td><%= contest.end_date.to_formatted_s(:short) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/contests/index.html.erb
<div>
  <% @contests.each do |contest| %>
    <div class="col-sm-6 col-md-4 col-lg-3" id="card_<%= contest.id %>">
      <div class="card">
          <%= image_tag contest.picture.thumb.url, class: "card-img-top" %>
          <div class="card-block">
              <h4 class="card-title"><%= contest.name %></h4>
              <div class="card-text">
                  <%= ActionView::Base.full_sanitizer.sanitize(contest.description).truncate(100) %>
              </div>
          </div>
          <div class="card-footer">
              <span class="float-right">End date</span>
              <span><i class=""></i><%= contest.end_date.to_formatted_s(:short) %></span>
              <button class="btn btn-primary float-right btn-sm pull-right btn_join" contest_id = <%= contest.id %> user_data = <%= current_user %> >Join</button>
          </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Competition</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
      <div class="container-fluid">
        <%= yield %>
      </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
	<footer class="navbar-fixed-bottom">
		<div class="panel panel-default">
			<div class="panel-footer text-center">
				Copyrights 2017, All rights reserved
			</div>
		</div>
	</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href=<%= root_path %>>COMPETITION</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li><a href= <%#= incomes_path %>>INCOMES</a></li> -->

        </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><a href=<%= dashboard_contests_path %> ><b>Dashboard</b></a></li>
        <% end %>
        <li class="dropdown">
          <% if user_signed_in? %>
          	<a href="#" class="dropdown-toggle" data-toggle="dropdown"><b><%= current_user.email %></b> <span class="caret"></span></a>
          <% else %>
          	<a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>Login</b> <span class="caret"></span></a>
          <% end %>
			<ul id="login-dp" class="dropdown-menu">
				<li>
					 <div class="row">
							<div class="col-md-12">
                 <form class="form" role="form" method="post" action="/users/sign_in" accept-charset="UTF-8" id="login-nav">
                    <div class="form-group">
                      <% if user_signed_in? %>
                        <a data-no-turbolink="true" rel="nofollow" data-method="delete" href= <%= destroy_user_session_path %> class="btn btn-primary btn-block" >Sign out</a>
                      <% else %>
        								Login via
        								<div class="social-buttons">
        									<a href= <%= user_facebook_omniauth_authorize_path %> class="btn btn-fb"><i class="fa fa-facebook"></i> Facebook</a>
        									<a href= <%= root_path %> class="btn btn-tw"><i class="fa fa-twitter"></i> Twitter</a>
        								</div>
                                        or
												<a href= <%= new_user_session_path %> class="btn btn-primary btn-block" >Sign in</a>
          							<div class="bottom text-center">
          								New here ? <a href=<%= new_user_registration_path %>><b>Join Us</b></a>
          							</div>
                      <% end %>
                    </div>
                 </form>
              </div>
					 </div>
				</li>
			</ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<script>
    $(document).ready(function(){
        (function() {
            "use strict";
            if (window.location && window.location.hash) {
                if (window.location.hash === '#_=_') {
                    window.location.hash = '';
                    history.pushState('', document.title, window.location.pathname); // nice and clean
                }
            }
        }());
    });
</script>